version: '{build}'
branches:
  only:
  - master
image: Visual Studio 2022
configuration: Release
platform:
- x64
- x86
init:
- ps: Update-AppveyorBuild -Version "$(Get-Date -format yyyy.MM.dd.HH.mm.ss)"
nuget:
  project_feed: true
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: >-
   
    cd C:\projects\sa-tools\

    buildSATools

    cd C:\projects\sa-tools\output
    
    7z a "C:\projects\sa-tools\SA Tools %PLATFORM%.7z" * -mx9
artifacts:
- path: SA Tools x64.7z
- path: SA Tools x86.7z

deploy: off